# Generated by Django 4.0.2 on 2022-02-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, to='bookrec.book'),
        ),
    ]
